### ISSUE TITLE
APO RoadMap

### ISSUE THREAD

**Issue by dxsup** [CloudDetail/apo#115]
欢迎大家对 APO RoadMap 提出建议！

### 增强故障根因分析
- [ ] 支持采集请求粒度的 OnCPU 和 OffCPU 火焰图数据，定位代码级原因
  - [ ] 基于 OnCPU 火焰图定位低效代码，例如多层循环、持续序列化
  - [ ] 基于 OffCPU 火焰图分析锁耗时、网络请求耗时、文件读写耗时的代码级原因
  - [ ] 基于持续剖析火焰图分析和优化程序性能
- [ ] 集成更多有价值的监控数据，进一步增强根因定位能力
### 利用大语言模型降低使用门槛，使产品更易用
- [ ] 利用大语言模型解释、分析告警事件等关联数据，重塑排障新交互，帮助用户充分利用数据价值
- [ ] 利用大语言模型解释火焰图数据，帮助用户更好得的解问题原因
### 数据库SQL执行耗时/性能分析
- [ ] 支持采集数据库应用的北极星指标，剖析 SQL 执行耗时构成
  - [ ] 识别 SQL 语句是 CPU 密集型，基于火焰图分析原因
  - [ ] 识别 SQL 语句是 IO 密集型，深入分析读写内容
  - [ ] 识别 SQL 语句是否因 CPU 限流而执行慢
### 全栈可观测性
- [ ] 支持日志告警
- [ ] 支持统计分析业务指标，从业务视角识别故障
- [ ] 支持采集前端监控数据，统计用户行为并识别问题，打通全栈可观测性
### 适配更多场景
- [ ] 支持更多编程语言的北极星指标
- [ ] 提高Go语言自动注入的稳定性
- [ ] eBPF 探针利用 BTF 特性适配更多内核
### 稳定性相关
- [ ] 优化数据采集 Agent 的资源开销

**Comment by cfy3133** [comment]
请问下能集成gala-ops火焰图嘛，感觉这个不错
https://mp.weixin.qq.com/s/WXArJbiA2nF93VyKSU71bA

**Comment by cfy3133** [comment]
还有一个问题，能够有办法针对Java线程池做监控嘛

**Comment by dxsup** [comment]
> 请问下能集成gala-ops火焰图嘛，感觉这个不错 https://mp.weixin.qq.com/s/WXArJbiA2nF93VyKSU71bA

我们以前调研过这个方案，对内核的要求偏高，目前针对Java语言正在采用[async-profiler](https://github.com/async-profiler/async-profiler)的方案，不依赖内核版本。

> 针对Java线程池做监控

感谢提出建议，我们调研一下

**Comment by dxsup** [comment]
目前不支持，为了能集成数据查询和检测，针对Dify做了二次开发

**Comment by bubbleatgit** [comment]
从DEMO站点看了一圈，这个软件真伟大！

**Comment by 31000023** [comment]
对dify支持的版本和otel-collector 的版本都太旧了。 更新的速度。 希望能重视。
